### ISSUE TITLE
Wireguard output not correct with multi deployment

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/terraform-provider-grid#425] opened 2022-12-16 16:06 UTC
### Terraform Version
```
➜  testvm terraform -v   
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/threefoldtech/grid v1.6.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- wireguard config output provided via:

```
output "wg_config" {
    value = grid_network.net1.access_wg_config
}
```

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    grid = {
      source = "threefoldtech/grid"
    }
  }
}

provider "grid" {
}

resource "grid_network" "net1" {
    nodes = [320, 321]
    ip_range = "10.138.0.0/16"
    name = "opstestnetw223"
    description = "ops testing network"
    add_wg_access = true
}
resource "grid_deployment" "d1" {
  node = 320
  network_name = grid_network.net1.name
  disks {
    name = "root"
    size = 25
  }
    vms {
    name = "opstst"
    description ="Ops testing image compatibility"
    flist = "https://hub.grid.tf/tf-official-vms/ubuntu-22.04-lts.flist"
    cpu = 2
    publicip = true
    publicip6 = true
    memory = 4096
    mounts {
        disk_name = "root"
        mount_point = "/data"
    }
    planetary = true
    env_vars = {
      SSH_KEY ="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYNeJXJV2FNEwuQz6e0jkKeqRbKWwftBKq+sjSTqa2x"
    }
  }
}
resource "grid_deployment" "d2" {
  node = 321
  network_name = grid_network.net1.name
  disks {
    name = "root"
    size = 25
  }
    vms {
    name = "opstst2"
    description ="Ops testing image compatibility"
    flist = "https://hub.grid.tf/tf-official-vms/ubuntu-22.04-lts.flist"
    cpu = 2
    publicip = true
    publicip6 = true
    memory = 4096
    mounts {
        disk_name = "root"
        mount_point = "/data"
    }
    planetary = true
    env_vars = {
      SSH_KEY ="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYNeJXJV2FNEwuQz6e0jkKeqRbKWwftBKq+sjSTqa2x"
    }
  }
}
output "wg_config" {
    value = grid_network.net1.access_wg_config
}
output "node1_vm1_ip" {
    value = grid_deployment.d1.vms[0].ip
}
output "public_ip" {
    value = grid_deployment.d1.vms[0].computedip
}
output "public_ip6" {
    value = grid_deployment.d1.vms[0].computedip6
}
output "ygg_ip" {
    value = grid_deployment.d1.vms[0].ygg_ip
}
```

### Expected Behavior
Deploy a vm and get a wireguard config, deploy a second vm and get the correct changed wireguard config.

```
output "wg_config" {
    value = grid_network.net1.access_wg_config
}
```

### Actual Behavior
Deplopying a vm with wg config works fine. Adding a second vm to the deployemnt also works fine, but the returned wireguard config is changed but not correctly printed after the deploy of the second vm:

This is the wg config after deploying the first and second vm:
```
[Interface]
Address = 100.64.138.2
PrivateKey = QHtrMicUKutqGEC3+7qf1P4EUDiqebNbAGrf8vPw0kg=
[Peer]
PublicKey = fJOJvn4a7/xrlQmiKiSEhpg0N3XzMIWRDMgYlpexxEY=
AllowedIPs = 10.138.0.0/16, 100.64.0.0/16
PersistentKeepalive = 25
Endpoint = 146.185.93.111:4607
```

This is the config after terraform refresh:
```
[Interface]
Address = 100.64.138.2
PrivateKey = QHtrMicUKutqGEC3+7qf1P4EUDiqebNbAGrf8vPw0kg=
[Peer]
PublicKey = 6+8Jpegt0JbVGFq/xyExHNmigeaLlvOJXszMVe/583c=
AllowedIPs = 10.138.0.0/16, 100.64.0.0/16
PersistentKeepalive = 25
Endpoint = 146.185.93.111:3447
```

### Steps to Reproduce
1. Deploy one vm with wireguard config enabled, save the wireguard config somewhere
2. Deploy a second vm inside the same terraform deployment and compare the printed wireguard config, it will be the same as the previous one (and will not work anymore)
3. Only a `terraform refresh` gives me the correct and working wg config

**Comment by AbdelrahmanElawady** [comment] 2022-12-27 11:05
I wasn't able to reproduce this issue after deploying on `mainnet` and `devnet` using the same tf file, the wireguard config is still the same after deploying one vm, two vms and running `terraform refresh`.

wireguard config using only one deployment:
```
[Interface]
Address = 100.64.138.2
PrivateKey = 4KVb0WmK+ysjLY67Jw4iYaj2brR/d4yh2LT4e9RCv1E=
[Peer]
PublicKey = YFkCgm0ZUbi4tZW3XU5Ds0AMEmIs3VTbk4IE2eaf4Sw=
AllowedIPs = 10.138.0.0/16, 100.64.0.0/16
PersistentKeepalive = 25
Endpoint = 146.185.93.125:5969
```

wireguard config after adding the other deployment:
```
[Interface]
Address = 100.64.138.2
PrivateKey = 4KVb0WmK+ysjLY67Jw4iYaj2brR/d4yh2LT4e9RCv1E=
[Peer]
PublicKey = YFkCgm0ZUbi4tZW3XU5Ds0AMEmIs3VTbk4IE2eaf4Sw=
AllowedIPs = 10.138.0.0/16, 100.64.0.0/16
PersistentKeepalive = 25
Endpoint = 146.185.93.125:5969
```

wireguard config after running `terraform refresh`:
```
[Interface]
Address = 100.64.138.2
PrivateKey = 4KVb0WmK+ysjLY67Jw4iYaj2brR/d4yh2LT4e9RCv1E=
[Peer]
PublicKey = YFkCgm0ZUbi4tZW3XU5Ds0AMEmIs3VTbk4IE2eaf4Sw=
AllowedIPs = 10.138.0.0/16, 100.64.0.0/16
PersistentKeepalive = 25
Endpoint = 146.185.93.125:5969
```

Also tried adding the new vm to the same deployment rather than a new deployment resource and still got the same wireguard config.

I'll close the issue for now since I couldn't reproduce it, but feel free to reopen this issue with more steps on how to reproduce it or if it happens again.

**Closed** 2022-12-27 11:05 UTC
Labels: type_bug

**Comment by coesensbert** [comment] 2022-12-27 12:58
> 

Did you also test the wireguard configs? To try to ssh to the vm's internal IP via WG.
