### ISSUE TITLE
Feature: Add support for deploying multiple master Kubernetes cluster

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/terraform-provider-grid#111] opened 2021-11-14 10:50 UTC
Add support for deploying multiple master Kubernetes clusters.
currently, we can specify one master block only.

**Comment by OmarElawady** [comment] 2021-11-14 10:51
duplicate of https://github.com/threefoldtech/terraform-provider-grid/issues/37

**Closed by OmarElawady** 2021-11-14 10:51 UTC
Labels: type_feature
