### ISSUE TITLE
Terraform terratest automated tests failure

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/terraform-provider-grid#239] opened 2022-04-28 10:07 UTC
Tested on testnet.

Some of the automated tests on the `development_terratest` branch fail with the following error 
```
│ Error: failed to fetch nodes from the grid proxy: json: cannot unmarshal number into Go struct field Node.updatedAt of type string
│ 
│   with grid_network.net1,
│   on main.tf line 17, in resource "grid_network" "net1":
│   17: resource "grid_network" "net1" {
│ 
╵}
```
They were tested on different nodes and gave the same error

the tests that fail are:
```
singlenode_test.go
kubernetes_test.go
```

**Comment by xmonader** [comment] 2022-12-26 18:07
duplicate of https://github.com/threefoldtech/terraform-provider-grid/issues/368

**Closed by xmonader** 2022-12-26 18:07 UTC
