### ISSUE TITLE
investigate other ways to convert schemas

### ISSUE THREAD

**Issue by MarioBassem** [threefoldtech/terraform-provider-grid#426] opened 2022-12-17 16:13 UTC
currently, converting between go structs and terraform's resourceData (map[string]interface{}) is done manually in the provider, while some already tested packages offer this functionality.
- struct to map[string]interface{} : https://github.com/fatih/structs
- map[string]interface{} to struct: https://github.com/mitchellh/mapstructure

**Comment by MarioBassem** [comment] 2022-12-22 17:06
the packages mentioned are made for general use and eventually may not be useful in our case.
maybe a new package needs to be developed to specifically get and set information from terraform resourceData maps.

**Comment by ashraffouda** [comment] 2023-02-22 11:16
duplicate of https://github.com/threefoldtech/terraform-provider-grid/issues/258

**Closed** 2023-02-22 11:34 UTC
Labels: type_feature
